### ISSUE TITLE
Unable to find file "@LugosiumOVHVPSMonitorBundle/Resources/config/config.yml"

### ISSUE THREAD

**Issue by airv-b** [lugosium/LugosiumOVHVPSMonitor#1]
Congrats and thank you for your bundle.
But, we dont have the "config.yml" in the folder Resources/config? 

Thank for your help.

Best Regards
Hervé

**Comment by lugosium** [comment]
Hello Hervé, 

Thank you for your feedback, will be fixed soon =)

Best regards,
Alban

**Comment by lugosium** [comment]
Hello,

It's fixed.
README updated. Version 1.0.0 released.
Let me know if you have an other issue.

Bests regards,
Alban

**Comment by airv-b** [comment]
It's OK .. But I have another problem.

**Comment by lugosium** [comment]
Hello,

Sorry to hear that, what's the new problem?

Bests regards

**Comment by airv-b** [comment]
Désolé je vais  vous expliquer mon probleme en francais ça sera plus simple. :)

Donc j'ai bien la page qui s'affiche, mais j'ai des les bulles qui tourne à l'infini .. 

En demarrant le google developer tools, j'ai vu que j'attaquais l'url suivante : "http://localhost/lugosium/monitor/rest/ovhVpsMonitor/getVpsMonitorData/%7B%22vpsName%22:%22**0**%22,%22periode%22:%22today%22%7D"
Hors, ça me fait une erreur 500 (logique vu que la valeur que j'ai dans le dashboard est à "0" au lieu du nom du vps (que je peux voir si je fais une GET /vps)
En ouvrant l'url je vois que le cela fonctionne si je remplace à la main (pour l'url) le 0 par le nom du vps (vpsXXXXXX.ovh.net)

Cependant je ne sais pas comment corriger le probleme

Merci beaucoup pour votre aide.

**Comment by lugosium** [comment]
Merci pour votre retour,

Juste au cas ou, vous êtes bien dans la zone EU et pas CA? 
Je fais plus de tests bientôt et vous tiens au courant.

**Comment by airv-b** [comment]
Oui je suis bien dans la zone EU ,donc j'ai bien mis 
lugosium_ovhvps_monitor:
    vps:
        zone: EU

Apres la seule difference, c'est que je n'ai pas utilisé l'url https://eu.api.ovh.com/createApp/ , car on n'a pas le Consumer Key sur cette url.

J'ai utilisé https://eu.api.ovh.com/createToken/

**Comment by lugosium** [comment]
Yes OK, de toutes façons si vous avez bien un résultat avec le getVps, et les donnés avec getVpsMonitorData ça vient du formulaire. 

J'ai mis à jour le bundle récemment pour qu'il fonctionne avec Symfony3, et notamment le formulaire, mais j'ai oublié de tester si il fonctionnait toujours avec Symfony2, je vais le faire dès ce soir. 

J'ai testé une installation Symfony 3 vide avec le bundle, ça fonctionne correctement pour ma part.

Merci!

**Comment by airv-b** [comment]
J'utilise Symfony 2.8.3 (donc théoriquement ça devrait pas poser de probleme ? )

**Comment by lugosium** [comment]
Quand je l'ai testé pour la première fois, le form ne fonctionnait pas, je me demande du coup si je n'ai pas cassé quelque chose en le faisant passé à Symfony 3, je testerai.

Donc si vous ouvrez cette URL après avoir remplacé le nom du VPS par le vôtre:

http://localhost/lugosium/monitor/rest/ovhVpsMonitor/getVps/%7B%22vpsName%22:%22vpsXXXXX.ovh.net%22,%22period%22:%22today%22%7D

Vous n'obtenez rien?

**Comment by airv-b** [comment]
Si si, c'est ce que je disais, en remplacant le 0 dans l'url .. j'obtiens le json (et tout ces chiffres ;) )

Dans l'ecran monitoring .. le vps est nommé aussi "0" (dans le form)

**Comment by lugosium** [comment]
> Si si, c'est ce que je disais, en remplacant le 0 dans l'url .. j'obtiens le json (et tout ces chiffres ;) )

L'URL à tester est censé retourner la liste de vos VPS OVH, elle est différente de l'autre (getVps et non getVpsMonitorData). 
C'est pour voir si il y a une réponse correcte de l'API OVH.
Si c'est le cas, ça viendrait donc bien du formulaire.

**Comment by airv-b** [comment]
Si tu veux je te mets une capture d'écran dans la soirée :)

**Comment by lugosium** [comment]
Non t'embêtes pas, je voulais juste être sur que l'url suivante te retourne bien la liste de tes VPS:

http://localhost/lugosium/monitor/rest/ovhVpsMonitor/getVps/%7B%22vpsName%22:%22vpsXXXXX.ovh.net%22,%22period%22:%22today%22%7D

Merci :)

**Comment by airv-b** [comment]
Merci :100:  à toi ;) .. on se tient au courant du coup :+1:

**Comment by lugosium** [comment]
Hello,

Ca devrait fonctionner maintenant, c'était bien un problème de form, c'est réglé dans la nouvelle release 1.0.1.

Bonne soirée et merci pour le retour!

**Comment by airv-b** [comment]
Testé et approuvé ! 

Je ferme l'issue :) MERCI beaucoup à toi. Si tu as besoin d'aide pour des tests sur d'autres bundles, dis moi :)

**Comment by lugosium** [comment]
Merci, avec plaisir :+1:
